# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hello_block/hello_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block || ORIG_REF_NAME==hello_block} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_clk_wiz_0_0/hello_block_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_clk_wiz_0_0 || ORIG_REF_NAME==hello_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_proc_sys_reset_0_0/hello_block_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_proc_sys_reset_0_0 || ORIG_REF_NAME==hello_block_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_microblaze_0_0/hello_block_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_microblaze_0_0 || ORIG_REF_NAME==hello_block_microblaze_0_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_microblaze_0_axi_periph_0/hello_block_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hello_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_microblaze_0_axi_intc_0/hello_block_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hello_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_microblaze_0_xlconcat_0/hello_block_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==hello_block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_mdm_1_0/hello_block_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_mdm_1_0 || ORIG_REF_NAME==hello_block_mdm_1_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_mig_7series_0_0/hello_block_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_mig_7series_0_0 || ORIG_REF_NAME==hello_block_mig_7series_0_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_axi_timer_0_0/hello_block_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_axi_timer_0_0 || ORIG_REF_NAME==hello_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_axi_uartlite_0_0/hello_block_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_axi_uartlite_0_0 || ORIG_REF_NAME==hello_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_xbar_0/hello_block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_xbar_0 || ORIG_REF_NAME==hello_block_xbar_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_ds_3/hello_block_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_ds_3 || ORIG_REF_NAME==hello_block_auto_ds_3} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_pc_3/hello_block_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_pc_3 || ORIG_REF_NAME==hello_block_auto_pc_3} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_ds_2 || ORIG_REF_NAME==hello_block_auto_ds_2} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_pc_2/hello_block_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_pc_2 || ORIG_REF_NAME==hello_block_auto_pc_2} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_cc_0/hello_block_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_cc_0 || ORIG_REF_NAME==hello_block_auto_cc_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_ds_1/hello_block_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_ds_1 || ORIG_REF_NAME==hello_block_auto_ds_1} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_pc_1/hello_block_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_pc_1 || ORIG_REF_NAME==hello_block_auto_pc_1} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_ds_0/hello_block_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_ds_0 || ORIG_REF_NAME==hello_block_auto_ds_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_pc_0/hello_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_pc_0 || ORIG_REF_NAME==hello_block_auto_pc_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_us_2/hello_block_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_us_2 || ORIG_REF_NAME==hello_block_auto_us_2} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_us_1/hello_block_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_us_1 || ORIG_REF_NAME==hello_block_auto_us_1} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_pc_4/hello_block_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_pc_4 || ORIG_REF_NAME==hello_block_auto_pc_4} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_auto_us_0/hello_block_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_auto_us_0 || ORIG_REF_NAME==hello_block_auto_us_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_dlmb_v10_0/hello_block_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_dlmb_v10_0 || ORIG_REF_NAME==hello_block_dlmb_v10_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_ilmb_v10_0/hello_block_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_ilmb_v10_0 || ORIG_REF_NAME==hello_block_ilmb_v10_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_dlmb_bram_if_cntlr_0/hello_block_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hello_block_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_ilmb_bram_if_cntlr_0/hello_block_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hello_block_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hello_block/ip/hello_block_lmb_bram_0/hello_block_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_block_lmb_bram_0 || ORIG_REF_NAME==hello_block_lmb_bram_0} -quiet] -quiet

# XDC: bd/hello_block/hello_block_ooc.xdc
