# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.cache/wt [current_project]
set_property parent.project_path C:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/imports/hdl/hello_block_wrapper.v
add_files C:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/hello_block.bd
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_clk_wiz_0_0/hello_block_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_clk_wiz_0_0/hello_block_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_clk_wiz_0_0/hello_block_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_proc_sys_reset_0_0/hello_block_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_proc_sys_reset_0_0/hello_block_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_proc_sys_reset_0_0/hello_block_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_microblaze_0_0/hello_block_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_microblaze_0_0/hello_block_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_microblaze_0_0/hello_block_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_microblaze_0_axi_intc_0/hello_block_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_microblaze_0_axi_intc_0/hello_block_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_microblaze_0_axi_intc_0/hello_block_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_mdm_1_0/hello_block_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_mdm_1_0/hello_block_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_mdm_1_0/hello_block_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_mig_7series_0_0/hello_block_mig_7series_0_0/user_design/constraints/hello_block_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_mig_7series_0_0/hello_block_mig_7series_0_0/user_design/constraints/hello_block_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_axi_timer_0_0/hello_block_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_axi_timer_0_0/hello_block_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_axi_uartlite_0_0/hello_block_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_axi_uartlite_0_0/hello_block_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_axi_uartlite_0_0/hello_block_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_xbar_0/hello_block_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_3/hello_block_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_3/hello_block_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_3/hello_block_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_pc_3/hello_block_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_pc_2/hello_block_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_cc_0/hello_block_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_cc_0/hello_block_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_cc_0/hello_block_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_1/hello_block_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_1/hello_block_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_1/hello_block_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_pc_1/hello_block_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_0/hello_block_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_0/hello_block_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_0/hello_block_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_pc_0/hello_block_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_2/hello_block_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_2/hello_block_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_2/hello_block_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_1/hello_block_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_1/hello_block_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_1/hello_block_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_pc_4/hello_block_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_0/hello_block_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_0/hello_block_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_us_0/hello_block_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_dlmb_v10_0/hello_block_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_dlmb_v10_0/hello_block_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_ilmb_v10_0/hello_block_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_ilmb_v10_0/hello_block_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_dlmb_bram_if_cntlr_0/hello_block_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_ilmb_bram_if_cntlr_0/hello_block_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_lmb_bram_0/hello_block_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/hello_block_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top hello_block_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hello_block_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hello_block_wrapper_utilization_synth.rpt -pb hello_block_wrapper_utilization_synth.pb"
