# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2.xci
# IP: The module: 'hello_block_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_block_auto_ds_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_block_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2.xci
# IP: The module: 'hello_block_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_block_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jonathan/Desktop/proj2/hello_world/helloWorld/helloWorld.srcs/sources_1/bd/hello_block/ip/hello_block_auto_ds_2/hello_block_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hello_block_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
